import { NextResponse } from "next/server";
import { Resend } from "resend";

export async function POST(request: Request) {
  try {
    const apiKey = process.env.RESEND_API_KEY;
    if (!apiKey) {
      return NextResponse.json(
        { error: "Email service is not configured. Please set the RESEND_API_KEY environment variable." },
        { status: 500 }
      );
    }

    const resend = new Resend(apiKey);
    const body = await request.json();
    const { name, email, hospital, phone, message } = body;

    // Validate required fields
    if (!name || !email || !hospital) {
      return NextResponse.json(
        { error: "Missing required fields (Name, Email, and Hospital are required)" },
        { status: 400 }
      );
    }

    // Determine target recipient email. Default to a notification email env variable
    // Resend's free tier with onboarding@resend.dev requires the recipient to be the verified account owner email.
    const toEmail = process.env.NOTIFICATION_EMAIL || "delivered@resend.dev";

    const { data, error } = await resend.emails.send({
      from: "HMS Web Form <onboarding@resend.dev>",
      to: toEmail,
      subject: `New Demo Booking Request: ${hospital}`,
      html: `
        <div style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; max-width: 600px; margin: 0 auto; padding: 24px; border: 1px solid #e2e8f0; border-radius: 16px; background-color: #ffffff; box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.05);">
          <div style="text-align: center; margin-bottom: 24px;">
            <h2 style="color: #0f172a; font-size: 24px; font-weight: 800; margin: 0; letter-spacing: -0.025em;">
              New Demo Request
            </h2>
            <p style="color: #64748b; font-size: 14px; margin-top: 4px; margin-bottom: 0;">
              AxonX Medtech HMS Portal
            </p>
          </div>
          
          <div style="background-color: #f8fafc; border-radius: 12px; padding: 20px; margin-bottom: 24px;">
            <table style="width: 100%; border-collapse: collapse;">
              <tr>
                <td style="padding: 8px 0; font-size: 13px; font-weight: 700; color: #475569; text-transform: uppercase; letter-spacing: 0.05em; width: 35%;">Full Name</td>
                <td style="padding: 8px 0; font-size: 15px; color: #0f172a; font-weight: 500;">${name}</td>
              </tr>
              <tr style="border-top: 1px solid #e2e8f0;">
                <td style="padding: 8px 0; font-size: 13px; font-weight: 700; color: #475569; text-transform: uppercase; letter-spacing: 0.05em;">Email</td>
                <td style="padding: 8px 0; font-size: 15px; color: #3b82f6; font-weight: 500;"><a href="mailto:${email}" style="color: #3b82f6; text-decoration: none;">${email}</a></td>
              </tr>
              <tr style="border-top: 1px solid #e2e8f0;">
                <td style="padding: 8px 0; font-size: 13px; font-weight: 700; color: #475569; text-transform: uppercase; letter-spacing: 0.05em;">Hospital</td>
                <td style="padding: 8px 0; font-size: 15px; color: #0f172a; font-weight: 500;">${hospital}</td>
              </tr>
              <tr style="border-top: 1px solid #e2e8f0;">
                <td style="padding: 8px 0; font-size: 13px; font-weight: 700; color: #475569; text-transform: uppercase; letter-spacing: 0.05em;">Phone</td>
                <td style="padding: 8px 0; font-size: 15px; color: #0f172a; font-weight: 500;">${phone || "Not provided"}</td>
              </tr>
            </table>
          </div>

          ${
            message
              ? `
            <div style="background-color: #eff6ff; border-radius: 12px; padding: 20px; border-left: 4px solid #3b82f6; margin-bottom: 24px;">
              <h3 style="margin-top: 0; margin-bottom: 8px; color: #1e3a8a; font-size: 14px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.05em;">
                Message / Details
              </h3>
              <p style="color: #1e40af; font-size: 14px; line-height: 1.6; margin: 0; white-space: pre-line;">
                ${message}
              </p>
            </div>
          `
              : ""
          }

          <div style="border-top: 1px solid #f1f5f9; padding-top: 16px; text-align: center;">
            <p style="font-size: 12px; color: #94a3b8; margin: 0;">
              This notification was generated by hms-website.
            </p>
          </div>
        </div>
      `,
    });

    if (error) {
      return NextResponse.json({ error }, { status: 400 });
    }

    return NextResponse.json({ success: true, data });
  } catch (error: any) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
